version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s %(levelname)s %(name)s - %(message)s"
        datefmt: "%d-%m-%y %H:%M"
    console:
        format: "%(asctime)s  %(levelname)s %(name)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: console
        stream: ext://sys.stdout

root:
    level: INFO
    handlers: [console]